
#ifndef VI_COMMANDER_ERRORS_H
#define VI_COMMANDER_ERRORS_H

enum ERRORS {ARGUMENTS_ERROR = 1,
    MEMORY_ERROR = 2,
    DIRECTORY_ERROR = 3,
    UNKNOWN_ERROR = 4,
    FILE_CREATION_ERROR
};

#endif //VI_COMMANDER_ERRORS_H
